package gov.naco.soch.entity;

import java.time.LocalDate;
import javax.annotation.Generated;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(Beneficiary.class)
public abstract class Beneficiary_ extends gov.naco.soch.entity.Auditable_ {

	public static volatile SingularAttribute<Beneficiary, String> caregiverPhoneNumber;
	public static volatile SetAttribute<Beneficiary, BeneficiaryTransitFacility> beneficiaryTransitFacilities;
	public static volatile SetAttribute<Beneficiary, ArtBeneficiaryLinkagePurposes> artBeneficiaryLinkagePurposes;
	public static volatile SingularAttribute<Beneficiary, String> artBenfSearchStr;
	public static volatile SingularAttribute<Beneficiary, String> mobileNumber;
	public static volatile SingularAttribute<Beneficiary, Boolean> isActive;
	public static volatile SingularAttribute<Beneficiary, IctcBeneficiary> ictcBeneficiary;
	public static volatile SetAttribute<Beneficiary, FacilityLinkedFacilityBeneficiary> facilityLinkedFacilityBeneficiaries;
	public static volatile SingularAttribute<Beneficiary, String> ostCode;
	public static volatile SingularAttribute<Beneficiary, MasterEducationLevel> guardianCaregiverHighestEducation_id;
	public static volatile SingularAttribute<Beneficiary, MasterOccupation> occupationId;
	public static volatile SingularAttribute<Beneficiary, MasterHivType> hivTypeId;
	public static volatile SetAttribute<Beneficiary, Dispensation> dispensations;
	public static volatile SetAttribute<Beneficiary, BeneficiaryVisitRegister> beneficiaryVisitRegisters;
	public static volatile SingularAttribute<Beneficiary, String> guardianCaregiverOthers;
	public static volatile SetAttribute<Beneficiary, BeneficiaryReferral> beneficiaryReferral;
	public static volatile SingularAttribute<Beneficiary, String> ostNumber;
	public static volatile SingularAttribute<Beneficiary, String> ostBenfSearchStr;
	public static volatile SingularAttribute<Beneficiary, Long> id;
	public static volatile SingularAttribute<Beneficiary, String> closePersonName;
	public static volatile SetAttribute<Beneficiary, ArtBeneficiary> artBeneficiary;
	public static volatile SingularAttribute<Beneficiary, String> deathReason;
	public static volatile SingularAttribute<Beneficiary, String> bankIfsc;
	public static volatile SetAttribute<Beneficiary, ArtBeneficiaryDueList> artBeneficiaryDueLists;
	public static volatile SingularAttribute<Beneficiary, String> fullName3;
	public static volatile SingularAttribute<Beneficiary, String> alternatePhonenumber;
	public static volatile SingularAttribute<Beneficiary, String> fullName2;
	public static volatile SingularAttribute<Beneficiary, String> caregiverName;
	public static volatile SingularAttribute<Beneficiary, MasterRelationType> masterRelationType;
	public static volatile SingularAttribute<Beneficiary, String> firstName;
	public static volatile SingularAttribute<Beneficiary, MasterMaritalStatus> maritalStatusId;
	public static volatile SingularAttribute<Beneficiary, MasterClientStatus> masterClientStatus;
	public static volatile SingularAttribute<Beneficiary, String> lastName;
	public static volatile SingularAttribute<Beneficiary, String> neoNatalComplications;
	public static volatile SingularAttribute<Beneficiary, TIBeneficiary> tiBeneficiary;
	public static volatile SingularAttribute<Beneficiary, Boolean> isLivingInRelationship;
	public static volatile SingularAttribute<Beneficiary, String> artNumber;
	public static volatile SetAttribute<Beneficiary, ArtBeneficiaryQueue> artBeneficiaryQueues;
	public static volatile SingularAttribute<Beneficiary, LocalDate> regDate;
	public static volatile SetAttribute<Beneficiary, ArtDispensation> artDispensations;
	public static volatile SetAttribute<Beneficiary, ArtBeneficiaryClinicalDetail> artBeneficiaryClinicalDetails;
	public static volatile SingularAttribute<Beneficiary, IctcDetail> ictcDetail;
	public static volatile SingularAttribute<Beneficiary, MasterMonthlyIncome> monthlyIncomeId;
	public static volatile SingularAttribute<Beneficiary, String> uid;
	public static volatile SingularAttribute<Beneficiary, Long> birthHistoryId;
	public static volatile SingularAttribute<Beneficiary, Address> caregiverAddressId;
	public static volatile SingularAttribute<Beneficiary, MasterGuardianCaregiver> guardianCaregiverId;
	public static volatile SetAttribute<Beneficiary, Transfer> transfers;
	public static volatile SingularAttribute<Beneficiary, String> infantEidCode;
	public static volatile SingularAttribute<Beneficiary, LocalDate> deathDate;
	public static volatile SingularAttribute<Beneficiary, DsrcBeneficiary> dsrcBeneficiary;
	public static volatile SingularAttribute<Beneficiary, String> bankAccountNumber;
	public static volatile SingularAttribute<Beneficiary, String> tiCode;
	public static volatile SetAttribute<Beneficiary, BeneficiaryFacilityMapping> beneficiaryFacilityMappings;
	public static volatile SingularAttribute<Beneficiary, MasterEducationLevel> educationLevelId;
	public static volatile SingularAttribute<Beneficiary, String> bankAccountName;
	public static volatile SetAttribute<Beneficiary, LinkedFacilityBeneficiary> linkedFacilityBeneficiaries;
	public static volatile SetAttribute<Beneficiary, BeneficiarySocialWelfareScheme> beneficiarySocialWelfareSchemes;
	public static volatile SingularAttribute<Beneficiary, Address> address;
	public static volatile SetAttribute<Beneficiary, BeneficiaryFamilyDetail> beneficiaryFamilyDetails;
	public static volatile SingularAttribute<Beneficiary, MasterHivStatus> hivStatusId;
	public static volatile SingularAttribute<Beneficiary, Boolean> isDelete;
	public static volatile SingularAttribute<Beneficiary, String> paediatricOtherVaccines;
	public static volatile SetAttribute<Beneficiary, ArtBeneficiaryFollowup> artBeneficiaryFollowups;
	public static volatile SingularAttribute<Beneficiary, String> otherEmploymentStatus;
	public static volatile SingularAttribute<Beneficiary, MasterGender> genderId;
	public static volatile SingularAttribute<Beneficiary, String> fullName;
	public static volatile SingularAttribute<Beneficiary, String> preArtNumber;
	public static volatile SingularAttribute<Beneficiary, LocalDate> dateOfBirth;
	public static volatile SingularAttribute<Beneficiary, String> dsrcBeneficiaryCode;
	public static volatile SingularAttribute<Beneficiary, MasterStayingWith> stayingWithId;
	public static volatile SetAttribute<Beneficiary, ArtBeneficiaryCounsellingNotes> artBeneficiaryCounsellingNotes;
	public static volatile SetAttribute<Beneficiary, ArtBeneficiaryIptAttDetails> artBeneficiaryIptAttDetails;
	public static volatile SingularAttribute<Beneficiary, Address> alternateAddressId;
	public static volatile SingularAttribute<Beneficiary, String> aadharNumber;
	public static volatile SingularAttribute<Beneficiary, TiOstBeneficiary> ostBeneficiary;
	public static volatile SingularAttribute<Beneficiary, Boolean> regularPartners;
	public static volatile SingularAttribute<Beneficiary, String> middleName;
	public static volatile SingularAttribute<Beneficiary, Double> birthWeight;
	public static volatile SingularAttribute<Beneficiary, String> stayingWithOthers;
	public static volatile SingularAttribute<Beneficiary, String> age;
	public static volatile SingularAttribute<Beneficiary, MasterBeneficiaryCategory> categoryId;

	public static final String CAREGIVER_PHONE_NUMBER = "caregiverPhoneNumber";
	public static final String BENEFICIARY_TRANSIT_FACILITIES = "beneficiaryTransitFacilities";
	public static final String ART_BENEFICIARY_LINKAGE_PURPOSES = "artBeneficiaryLinkagePurposes";
	public static final String ART_BENF_SEARCH_STR = "artBenfSearchStr";
	public static final String MOBILE_NUMBER = "mobileNumber";
	public static final String IS_ACTIVE = "isActive";
	public static final String ICTC_BENEFICIARY = "ictcBeneficiary";
	public static final String FACILITY_LINKED_FACILITY_BENEFICIARIES = "facilityLinkedFacilityBeneficiaries";
	public static final String OST_CODE = "ostCode";
	public static final String GUARDIAN_CAREGIVER_HIGHEST_EDUCATION_ID = "guardianCaregiverHighestEducation_id";
	public static final String OCCUPATION_ID = "occupationId";
	public static final String HIV_TYPE_ID = "hivTypeId";
	public static final String DISPENSATIONS = "dispensations";
	public static final String BENEFICIARY_VISIT_REGISTERS = "beneficiaryVisitRegisters";
	public static final String GUARDIAN_CAREGIVER_OTHERS = "guardianCaregiverOthers";
	public static final String BENEFICIARY_REFERRAL = "beneficiaryReferral";
	public static final String OST_NUMBER = "ostNumber";
	public static final String OST_BENF_SEARCH_STR = "ostBenfSearchStr";
	public static final String ID = "id";
	public static final String CLOSE_PERSON_NAME = "closePersonName";
	public static final String ART_BENEFICIARY = "artBeneficiary";
	public static final String DEATH_REASON = "deathReason";
	public static final String BANK_IFSC = "bankIfsc";
	public static final String ART_BENEFICIARY_DUE_LISTS = "artBeneficiaryDueLists";
	public static final String FULL_NAME3 = "fullName3";
	public static final String ALTERNATE_PHONENUMBER = "alternatePhonenumber";
	public static final String FULL_NAME2 = "fullName2";
	public static final String CAREGIVER_NAME = "caregiverName";
	public static final String MASTER_RELATION_TYPE = "masterRelationType";
	public static final String FIRST_NAME = "firstName";
	public static final String MARITAL_STATUS_ID = "maritalStatusId";
	public static final String MASTER_CLIENT_STATUS = "masterClientStatus";
	public static final String LAST_NAME = "lastName";
	public static final String NEO_NATAL_COMPLICATIONS = "neoNatalComplications";
	public static final String TI_BENEFICIARY = "tiBeneficiary";
	public static final String IS_LIVING_IN_RELATIONSHIP = "isLivingInRelationship";
	public static final String ART_NUMBER = "artNumber";
	public static final String ART_BENEFICIARY_QUEUES = "artBeneficiaryQueues";
	public static final String REG_DATE = "regDate";
	public static final String ART_DISPENSATIONS = "artDispensations";
	public static final String ART_BENEFICIARY_CLINICAL_DETAILS = "artBeneficiaryClinicalDetails";
	public static final String ICTC_DETAIL = "ictcDetail";
	public static final String MONTHLY_INCOME_ID = "monthlyIncomeId";
	public static final String UID = "uid";
	public static final String BIRTH_HISTORY_ID = "birthHistoryId";
	public static final String CAREGIVER_ADDRESS_ID = "caregiverAddressId";
	public static final String GUARDIAN_CAREGIVER_ID = "guardianCaregiverId";
	public static final String TRANSFERS = "transfers";
	public static final String INFANT_EID_CODE = "infantEidCode";
	public static final String DEATH_DATE = "deathDate";
	public static final String DSRC_BENEFICIARY = "dsrcBeneficiary";
	public static final String BANK_ACCOUNT_NUMBER = "bankAccountNumber";
	public static final String TI_CODE = "tiCode";
	public static final String BENEFICIARY_FACILITY_MAPPINGS = "beneficiaryFacilityMappings";
	public static final String EDUCATION_LEVEL_ID = "educationLevelId";
	public static final String BANK_ACCOUNT_NAME = "bankAccountName";
	public static final String LINKED_FACILITY_BENEFICIARIES = "linkedFacilityBeneficiaries";
	public static final String BENEFICIARY_SOCIAL_WELFARE_SCHEMES = "beneficiarySocialWelfareSchemes";
	public static final String ADDRESS = "address";
	public static final String BENEFICIARY_FAMILY_DETAILS = "beneficiaryFamilyDetails";
	public static final String HIV_STATUS_ID = "hivStatusId";
	public static final String IS_DELETE = "isDelete";
	public static final String PAEDIATRIC_OTHER_VACCINES = "paediatricOtherVaccines";
	public static final String ART_BENEFICIARY_FOLLOWUPS = "artBeneficiaryFollowups";
	public static final String OTHER_EMPLOYMENT_STATUS = "otherEmploymentStatus";
	public static final String GENDER_ID = "genderId";
	public static final String FULL_NAME = "fullName";
	public static final String PRE_ART_NUMBER = "preArtNumber";
	public static final String DATE_OF_BIRTH = "dateOfBirth";
	public static final String DSRC_BENEFICIARY_CODE = "dsrcBeneficiaryCode";
	public static final String STAYING_WITH_ID = "stayingWithId";
	public static final String ART_BENEFICIARY_COUNSELLING_NOTES = "artBeneficiaryCounsellingNotes";
	public static final String ART_BENEFICIARY_IPT_ATT_DETAILS = "artBeneficiaryIptAttDetails";
	public static final String ALTERNATE_ADDRESS_ID = "alternateAddressId";
	public static final String AADHAR_NUMBER = "aadharNumber";
	public static final String OST_BENEFICIARY = "ostBeneficiary";
	public static final String REGULAR_PARTNERS = "regularPartners";
	public static final String MIDDLE_NAME = "middleName";
	public static final String BIRTH_WEIGHT = "birthWeight";
	public static final String STAYING_WITH_OTHERS = "stayingWithOthers";
	public static final String AGE = "age";
	public static final String CATEGORY_ID = "categoryId";

}

